name: da-tools

channels:
  - nvidia
  - pytorch
  - conda-forge

dependencies:
  - python=3.9
  - pip
  - pytorch-cuda=11.7
  - pytorch
  - pre-commit
  - black
  - isort
  - flake8
  - tensorboard
  - torchvision>=0.14
  - pytorch-lightning>=2
  - hydra-core=1.3
  - matplotlib
  - ipython
  - jupyterlab
  - rich
  - gitpython
  - coverage
  - tqdm
  - pylint
  - sphinx<7.0.0
  - sphinx-autoapi
  - setuptools_scm
  - pytest
  - pytest-cov
  - git
  - h5py
  - pip:
      - onnxruntime-gpu
      - torch-tb-profiler
      - sphinx-typo3-theme # sphinx theme
      - seed-intersphinx-mapping
      - tensordict==0.8.3
      - nbformat
      - nbconvert
      - git+https://codebase.helmholtz.cloud/m-dml/mdml-sim@main
